name: Publish

on:
  # Github release triggers publish
  release:
    types: [created]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      vsixPath: ${{ steps.buildVsx.outputs.vsixPath }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - uses: HaaLeo/publish-vscode-extension@v1
        id: buildVsx
        with:
          pat: stub
          dryRun: true
      - uses: actions/upload-artifact@v2
        with:
          name: vsix
          path: ${{ steps.buildVsx.outputs.vsixPath }}

  publish-to-open-vsx:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download vsix
        uses: actions/download-artifact@v2
        with:
          name: vsix
      - uses: HaaLeo/publish-vscode-extension@v1
        id: publishToOpenVSX
        with:
          pat: ${{ secrets.OPEN_VSX_TOKEN }}
          extensionFile: ${{ needs.build.outputs.vsixPath }}
          skipDuplicate: true

  publish-to-vs-marketplace:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download vsix
        uses: actions/download-artifact@v2
        with:
          name: vsix
      - uses: HaaLeo/publish-vscode-extension@v1
        with:
          pat: ${{ secrets.VS_MARKETPLACE_TOKEN }}
          registryUrl: https://marketplace.visualstudio.com
          extensionFile: ${{ needs.build.outputs.vsixPath }}
          skipDuplicate: true
